spring:
  application:
    name: ventas

  config:
    import: "optional:configserver:http://localhost:7071"

  datasource:
    url: jdbc:mysql://localhost:3306/ventasdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html