spring:
  application:
    name: user

  profiles:
    active: dev

  cloud:
    discovery:
      enabled: true

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:7071}"

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html